### ISSUE TITLE
Unable to get IPv6 with prefix from Framed-IPv6-Prefix attribute

### ISSUE THREAD

**Issue by dav-komarek** [layeh/radius#118]
### Description
When packet containing following bytes is parsed `61 0a 00 40 20 01 15 30 10 0e` using `rfc3162.FramedIPv6Prefix_Get`, the error is returned in the inner function `radius.IPv6Prefix` on the line https://github.com/layeh/radius/blob/master/attribute.go#L471. But the provided IPv6 is valid address (`2001:1530:100e::/64`)

### Proposal
The function `radius.IPv6Prefix` should be able to parse IPv6 of the specified format.

Apparently the check for the length of the byte array (linked) is wrong and should be replaced with check that the prefix is at most 128 bits long.

**Comment by u873838** [comment]
Should be fixed with 1006025d24f8fdd5b5ee8b3c15a714e6b24baaab.

**Comment by dav-komarek** [comment]
Please check https://github.com/layeh/radius/commit/1006025d24f8fdd5b5ee8b3c15a714e6b24baaab#r134862652.

**Comment by jamiesun** [comment]
Follow-up: #119 reported that the fix here rejects prefixes whose bits beyond the `Prefix-Length` are non-zero. #141 addresses that by clearing those bits on decode rather than erroring, while keeping this issue's tolerance for omitted trailing zero bytes.
