### ISSUE TITLE
redius-dict-gen: duplicate attribute

### ISSUE THREAD

**Issue by shamanis** [layeh/radius#17]
I'm trying to generate a dictionary:
```bash
go run main.go -package redback /usr/share/freeradius/dictionary.redback
```
and get an error:
```bash
radius-dict-gen: dictionary: parse error in /usr/share/freeradius/dictionary.redback:278: duplicate attribute "Tunnel-Flow-Control"
exit status 1
```

How to fix it?

Dictionary is default from FreeRADIUS.

**Comment by bontibon** [comment]
Please update radius (`go get -u layeh.com/radius/...`) and then try running:

```bash
go run main.go -package redback -ignore Tunnel-Hello-Timer /usr/share/freeradius/dictionary.redback
```

**Comment by shamanis** [comment]
Thx! It's work for me!

**Comment by bontibon** [comment]
@shamanis Yeah, I see that the dictionary file contains a set of new attribute names and old attribute names whose generated helper name would be the same. I'll open another ticket to track that particular issue.
