### ISSUE TITLE
radius-dict-gen fails for 3GPP dictionary

### ISSUE THREAD

**Issue by borud** [layeh/radius#20]
Hi,

I tried to run `radius-dict-get` on the 3GPP dictionary from the FreeRADIUS project and it fails with 

    radius-dict-gen: dictionary: parse error in /Users/borud/go/src/ghe.telenordigital.com/TelenorDigital/horde/radius/3gpp/dictionary.3gpp:28: unknown attribute type "byte

The file is at:  https://github.com/redBorder/freeradius/blob/master/share/dictionary.3gpp

After changing `bytes` to `octets` I get the following error message:

    radius-dict-gen: 99:6: expected 'IDENT', found 'INT' 3 (and 10 more errors)

I'm confused.  What am I doing wrong?  Is the issue that the vendor starts with a number? Is this a bug? How can I get around this?

**Comment by bontibon** [comment]
> Is the issue that the vendor starts with a number? Is this a bug?

Yes and yes.  I'll try to push a fix for that today.

**Comment by borud** [comment]
Seems to work now!  Thanks for the rapid response.
