### ISSUE TITLE
Attributes encoding order matters when generating HMAC MD5 hash code

### ISSUE THREAD

**Issue by dbainbri-ciena** [layeh/radius#27]
Currently, the attributes are stored as a map, which means when the attributes are encoded to wire format the order in which they are encoded is random (or at least can't be relied upon). Unfortunately, this means the order in which attributes are added can impact the encoding and thus a hash generated against one encoding can be invalided by another. The specific use case is:

1. create packet
2. set authenticator attribute to all zeros
3. encode to bytes
4. generate hmac.md5 authenticator
5. set authenticator attribute to generated value
6. encode to bytes to send to radius

The encoding at 3 and 6 can generate the attributes in different order and thus the hash generated at step 4 is no longer valid (all the time).

(pull request coming soon)

**Comment by bontibon** [comment]
Is this HMAC you are generating part of a particular RADIUS extension? You probably have noticed `radius.IsAuthenticResponse`, which operates on the wire representation of the packet rather than the decoded `radius.*Packet`.

Would adding the ability customize the server and client's validation function be helpful?

**Comment by dbainbri-ciena** [comment]
When I generate a RADIUS request, I need to set the authenticator attribute. Per the spec (I think) and per experience (against FreeRADIUS), the authenticator value is generated using an HMAC.MD5 encoding (i.e. using the secret to create an MD5 16 byte hash). 

Before I modified the `Attributes.encodeTo` func to encode in a key sorted order, I noticed the `[]byte` I used to generate the hash (i.e. the encoding of the packet) was different from what was captured via `tcpdump` on the RADIUS server. And as the attribute order was different, the computed hash was no longer valid and the server drop/ignored the packet.

So the issue I was seeing was not so much validating packets from the server as generating correct packets so the server did not drop/ignore them.

**Comment by dbainbri-ciena** [comment]
That is quite possible. I didn't see in the code, and perhaps I missed it, where the authenticator attribute was being generated and set.

**Comment by bontibon** [comment]
As a rule of thumb, you do not need to touch the Packet.Authenticator field.  It automatically gets populated with random values when created with `radius.New`, and the MD5 hash is automatically calculated on outgoing and incoming packets via Client.Exchange and ResponseWriter.Write, respectively.

**Comment by dbainbri-ciena** [comment]
This is not the `Packet.Authenticator` field, this is the `rfc2869.MessageAuthenticator_Set`. The `Packet.Authenticator` is working fine, as expected.

**Comment by bontibon** [comment]
OK, I understand the issue now. Thank you for explaining it through.

Out of curiosity, what does your function look like that encodes the packet, generates the HMAC, and writes the HMAC back to the encoded packet?

**Comment by dbainbri-ciena** [comment]
```
