### ISSUE TITLE
server's Handler will be executed whether the secret is correct or not

### ISSUE THREAD

**Issue by Lostvincent** [layeh/radius#34]
Is that a feature?
Similar problem in this issus #11 , last replied on Mar 27

**Comment by bontibon** [comment]
Yes, this is the nature of the AccessRequest packet.

You may find that adding Message-Authenticator attribute to your packet will help determine whether a request has an invalid User-Password value or an invalid secret.

**Comment by duramen** [comment]
@bontibon Can I get the AccessRequest's secret? And how?

**Comment by bontibon** [comment]
@duramen Do you mean you want to access the secret that was returned from the server's `SecretSource` for the given request?

**Comment by duramen** [comment]
> 
> 
> @duramen Do you mean you want to access the secret that was returned from the server's `SecretSource` for the given request?

I am so sorry.

I used to want to get the client's key, but now I look at the principle of radius protocol PAP encryption, I know it can't be obtained.
