### ISSUE TITLE
status-server request

### ISSUE THREAD

**Issue by ilyam8** [layeh/radius#47]
Hi. I need to send `status-server` req to freeradius server.

via `radclient`

```
xxx@yyy[~]cat rad
Message-Authenticator = 0x00
FreeRADIUS-Statistics-Type = 15
Response-Packet-Type = Access-Accept

xxx@yyy[~]radclient -t 1 -r 1 127.0.0.1:18121 status adminsecret -x -f rad
Sending Status-Server of id 2 to 127.0.0.1 port 18121
	Message-Authenticator = 0x00000000000000000000000000000000
	FreeRADIUS-Statistics-Type = 15
rad_recv: Access-Accept packet from host 127.0.0.1 port 18121, id=2, length=428
	FreeRADIUS-Total-Access-Requests = 7706
	FreeRADIUS-Total-Access-Accepts = 7691
	FreeRADIUS-Total-Access-Rejects = 9
        ...
```

I feel like i am missing something, but I can't figure out how to do this using this library and whether it can be done at all.

Please help :pray:

**Comment by bontibon** [comment]
What specifically are you having trouble with? I don't see any Go code in your question.

**Comment by ilyam8** [comment]
i am having trouble with creating a packet.

i understand that i need to:
 * create a new packet with status server code
 * add/set `FreeRADIUS-Statistics-Type = 15`
 * add/set `Message-Authenticator = 0x00`

i found that
 * 80 | Message-Authenticator | string
 * 127|  FreeRADIUS-Statistics-Type| integeer


```go
	packet := radius.New(radius.CodeStatusServer, []byte(`adminsecret`))
       // VALUE	    FreeRADIUS-Statistics-Type	Authentication		 1
	packet.Set(radius.Type(127), radius.NewInteger(1))
```

i don;t know how to add `Message-Authenticator = 0x00`

**Comment by bontibon** [comment]
The library does not automatically populate Message-Authenticator with the packet's HMAC. See https://github.com/layeh/radius/issues/43#issuecomment-441491535.

**Comment by ilyam8** [comment]
Nice! It works.

btw why all imports `layeh.com/radius` and not `github.com/layeh/radius` ?

i can't use the library with go mod.

what i did:
 * add imports `"layeh.com/radius"`, `"layeh.com/radius/rfc2865"`. Executed `go mod`. No effect.
 * changed imports to `"github.com/layeh/radius"`, `"github.com/layeh/radius/rfc2865"`. Executed `go mod`. Success.

But since rfc2865 uses `layeh/radius` i can't build my program.

`build github.com/ilyam8/playground: cannot find module for path layeh.com/radius`

**Comment by ilyam8** [comment]
if someone will be looking for the wroking code

```go
packet := radius.New(radius.CodeStatusServer, []byte(secret))

_ = PacketType_Set(packet, PacketType_Value_AccessAccept)
_ = FreeRADIUSStatisticsType_Set(packet, FreeRADIUSStatisticsType_Value_Authentication)
_ = rfc2869.MessageAuthenticator_Set(packet, make([]byte, 16))

hash := hmac.New(md5.New, packet.Secret)
encode, _ := packet.Encode()
hash.Write(encode)

_ = rfc2869.MessageAuthenticator_Set(packet, hash.Sum(nil))
```

**Comment by bontibon** [comment]
All of your references, including the ones in go.mod and go.sum, file should be to layeh.com/radius, not github.com/layeh/radius.
