### ISSUE TITLE
How to use CHAP or MSCHAPv2 authentication mechanism?

### ISSUE THREAD

**Issue by kamushadenes** [layeh/radius#57]
Hello,

I'm trying to use CHAP to implement an LDAP MFA using Yubikey, but when I perform CHAPPassword_GetString I get some garbled mess.

My knowledge in RADIUS internals is lacking, unfortunately... Likely, I need to decode/decrypt that in some way using the shared secret.

I took a look at the godoc for both the main package and the rfc2865, but I'm not able to figure out how to do that. I also couldn't find RFC 1661 (CHAP) or RFC 2759 (MS-CHAP v2) sub packages to perhaps get some light.

Can someone please provide an example? One using MSCHAPv2 would be even better!

**Comment by kamushadenes** [comment]
Testing is being done using:

```echo 'User-Name="kamushadenes",Chap-Password="BLABLABLA"' | radclient  -x localhost:1812 auth SECRET```

**Comment by ScruffyPants** [comment]
Well, I had the same question myself and in the end had to make my own function to check against CHAP. I am using rfc2865 and managed to do it by reading it's documentation. Firstly, CHAP (at least in my case) uses MD5 and the way checksum is calculated is MD5(CHAP-ID + cleartext password + authenticator). CHAP-ID comes from first byte of CHAP-Challenge (it's length is 17 bytes, first byte is CHAP-ID the next 16 is the actual CHAP-Challenge against which you have to compare your checksum), the authenticator is either received from r.Packet.Authenticator (where r is *radius.Request) or the whole CHAP-Challenge is used. Knowing this info I made a function that looks like this: 
```
func checkAgainstCHAP(password, authenticator, chapChallenge []byte) bool {
	h := md5.New()
	h.Write(chapChallenge[:1])
	h.Write(password)
	h.Write(authenticator)
	answer := h.Sum(nil)
	if len(answer) != len(chapChallenge[1:]) {
		return false
	}
	for i := range answer {
		if answer[i] != chapChallenge[i+1] {
			return false
		}
	}
	return true
}
```
As you can see `h` is my hash, h.Write() method writes bytes into buffer (concatenation) and I check each byte of both checksums in for loop to check if they are equal. I return `true` if they match and that means user entered correct password. `password` in the function parameters is the cleartext password btw. Hope this helps.

**Comment by zonque** [comment]
For MS-CHAPv2, I just submitted #61

**Comment by zonque** [comment]
I really don't get you question. As I said before, Radioauth takes a plain-text password from a account store and feeds it into the MSCHAPv2 related functions, starting here: https://github.com/holoplot/radioauth/blob/7caeddc60e4c597f812b86f446626f6836728581/cmd/radioauth/radius-server.go#L36

This is a full-fledged and complete server application, what question is there left to answer? You could just use it as-is in favour of Google's LDAP if you want.

**Comment by undeadindustries** [comment]
Thanks for the response. I found my answer. Google LDAP doesn't supply passwords in a return. So it's probably not going to work. Thanks again!

**Comment by kamushadenes** [comment]
I have since moved from that project, but from the answers provided I believe this question has been answered. Closing the issue, thank you very much for your time!
