### ISSUE TITLE
How to add a Vendor Specific Attribute ?

### ISSUE THREAD

**Issue by jiahuat** [layeh/radius#7]
Radius dictionary like this:
VENDOR 800 Xylan
VENDORATTR 800 Vattribute 103 string

At Client side，i want to construct a radius packet which contain the Vatrribute? How to do it?
i tried like this:
e.g  Vatrribute is "hello"

        hello, _ := radius.NewString("hello")
	helloAttr := radius.NewVendorSpecific(103, hello)
	vsa := radius.NewVendorSpecific(800, helloAttr)
	packet.Set(rfc.VendorSpecific_Type, vsa)

But it does not work, what should i do?

**Comment by bontibon** [comment]
Sorry for not having the VSA support added to radius-dict-gen yet; it will make working with VSA much easier (I should try to have that done soon).

In the mean time, you can do something like the following:

```go
hello, _ := radius.NewString("hello")
helloAttr := make(radius.Attribute, 2 + len(hello))
helloAttr[0] = byte(103)
helloAttr[1] = byte(len(hello))
copy(helloAttr[2:], hello)
vsa := radius.NewVendorSpecific(800, helloAttr)
packet.Set(rfc.VendorSpecific_Type, vsa)
```

**Comment by jiahuat** [comment]
Thanks for your help!!!  it woks!
One more thing about the above code,
helloAttr[1] = byte(len(hello))  Should be like this: helloAttr[1] = byte(len(helloAttr))

**Comment by bontibon** [comment]
@jiahuat I've added Vendor-Specific generation support in 999ce50921b0a6766d542678d1d67fcd95db3b37. If you have a chance, please try it out and let me know if anything isn't working.
