### ISSUE TITLE
server-packet logging request

### ISSUE THREAD

**Issue by gorhamc** [layeh/radius#76]
I noticed a TODO comment for adding a logger in server-packet.go. I'm interested in helping out with this, but wanted to clarify a few things first. 

1. Is this something you would welcome a PR for?
2. If so, is there a preferred logger? My preference is typically [glog](https://github.com/golang/glog), but happy to use something else if preferred.

**Comment by bontibon** [comment]
The logging would only be for things like errors, not debugging information like successful connections or packet responses.

The net/http.*Server just uses the log package for this (see net/http.*Server.ErrorLog). What are you thoughts on that?

**Comment by gorhamc** [comment]
I haven't used that package before so I don't have much of an opinion on it. I'm happy to give it a go. 

Just logging errors sounds good to me. There's been times when logging validation failures (i.e IsAuthenticRequest/Response=false) would be useful but I think that may fall under debug logging?
