### ISSUE TITLE
Attribute "Class" is not handled properly

### ISSUE THREAD

**Issue by PawlikMateusz** [layeh/radius#89]
Hello, 
I'm trying to use the library to save accounting information in FreeRADIUS server.  I have problem with the "Class" attribute. I set the Class attribute with `rfc2865.Class_SetString(pkt, "test123")`. When I checked Class value in sniffed packet and in FreeRADIUS database I got different value like Class=74657374313233. Other attributes like User-Name, NAS-IP-Address etc. works perfectly fine. 

I also tried to set Class value by using `rfc2865.Class_AddString` and `rfc2865.Class_Set`, result was the same.

Would it be possible to verify this behaviour?

**Comment by bontibon** [comment]
RFC 2865 states (emphasis mine):

> 5.25.  Class
> 
>    Description
> 
>    This Attribute is available to be sent by the server to the client
>    in an Access-Accept and SHOULD be sent unmodified by the client to
>    the accounting server as part of the Accounting-Request packet if
>    accounting is supported.  **The client MUST NOT interpret the
>    attribute locally.**
> 
>    A summary of the Class Attribute format is shown below.  The fields
>    are transmitted from left to right.
> 
>      0                   1                   2
>      0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
>     +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
>     |     Type      |    Length     |  String ...
>     +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-
> 
>    Type
> 
>    25 for Class.
> 
>    Length
> 
>  \>= 3
> 
>    String
> 
>    The String field is one or more octets.  **The actual format of the
>    information is site or application specific, and a robust
>    implementation SHOULD support the field as undistinguished octets.**
> 
>   The codification of the range of allowed usage of this field is
>   outside the scope of this specification.

What you are seeing are just the byte values from the string you are sending. Any examining that you doing with radclient or Wireshark is probably following the spec by not rendering the attribute bytes as text. Does that make sense, or have I misunderstood something?

**Comment by PawlikMateusz** [comment]
Ok, so everything looks fine, sorry for oversight from my site and thanks for fast reply
