### ISSUE TITLE
Support for Asynchronous callback support for Radius-Client 

### ISSUE THREAD

**Issue by ping2balaji** [layeh/radius#92]
I see layeh/radius client module perform radius-client request in blocking mode to radius-server. 
Is there any way in this project where we can do asynchronous request and get a callback fn when radius-server sends back radius-response? 

Please clarify.

**Comment by bontibon** [comment]
If you want the results asynchronously, call the radius client in a go routine.

**Comment by ping2balaji** [comment]
Thanks @bontibon , that makes sense.
Btw, does the project support following:
1. LDAP integration to perform AD based authentication?
2. Radius Proxy support where layeh will act as server to NAS device and also client to the actual AAA radius server?
3. HTTP REST interface support to convert radius messages to rest apis?
Can you please clarify above?

**Comment by bontibon** [comment]
1. No
2. You will have to write the proxy code yourself
3. No

**Comment by ping2balaji** [comment]
Thanks @bontibon  for the comments. I will close this issue now with your clarification.
