### ISSUE TITLE
`layeh.com/radius` vanity import redirect is broken

### ISSUE THREAD

**Issue by jeffwidman** [layeh/radius#98]
The `layeh.com/radius` vanity import is currently broken:
```
$ GOPRIVATE=* go list -m -versions layeh.com/radius
go list -m: unrecognized import path "layeh.com/radius": parse https://layeh.com/radius?go-get=1: no go-import meta tags (meta tag https://layeh.com/radius did not match import path layeh.com/radius)
```

Note that in order to see this, you have to set `GOPRIVATE=*`, likely because of the global module proxy cache.

More details here: https://github.com/dependabot/dependabot-core/issues/4423 and hat tip to @mctofu for tracking down the underlying issue in that thread.

**Comment by ghost** [comment]
Sorry about that. It should be fixed now.

**Comment by jeffwidman** [comment]
Wow, that was fast! Thanks!
