### ISSUE TITLE
pap: ERROR: Cleartext password does not match "known good" password

### ISSUE THREAD

**Issue by arun0704** [layeh/radius#99]
Please help in resolving this issue. Testing with FreeRadius. No doubt on Free radius server configurations because when i use radtest with same data Authentication is passed.

But when i am testing with Radius lib, seeing this issue.
Ready to process requests
(0) Received Access-Request Id 90 from [::1]:58292 to [::1]:1812 length 43
(0)   User-Name = "ems"
(0)   User-Password = "\016Evk\2534x\206H|ܴ\2532M\310"
(0) # Executing section authorize from file /etc/raddb/sites-enabled/default
(0)   authorize {
(0)     policy filter_username {
(0)       if (&User-Name) {
(0)       if (&User-Name)  -> TRUE
(0)       if (&User-Name)  {
(0)         if (&User-Name =~ / /) {
(0)         if (&User-Name =~ / /)  -> FALSE
(0)         if (&User-Name =~ /@[^@]*@/ ) {
(0)         if (&User-Name =~ /@[^@]*@/ )  -> FALSE
(0)         if (&User-Name =~ /\.\./ ) {
(0)         if (&User-Name =~ /\.\./ )  -> FALSE
(0)         if ((&User-Name =~ /@/) && (&User-Name !~ /@(.+)\.(.+)$/))  {
(0)         if ((&User-Name =~ /@/) && (&User-Name !~ /@(.+)\.(.+)$/))   -> FALSE
(0)         if (&User-Name =~ /\.$/)  {
(0)         if (&User-Name =~ /\.$/)   -> FALSE
(0)         if (&User-Name =~ /@\./)  {
(0)         if (&User-Name =~ /@\./)   -> FALSE
(0)       } # if (&User-Name)  = notfound
(0)     } # policy filter_username = notfound
(0)     policy filter_password {
(0)       if (&User-Password && 	   (&User-Password != "%{string:User-Password}")) {
(0)       EXPAND %{string:User-Password}
(0)          --> ?Evk?4x?H|ܴ?2M?
(0)       if (&User-Password && 	   (&User-Password != "%{string:User-Password}"))  -> FALSE
(0)     } # policy filter_password = notfound
(0)     [preprocess] = ok
(0)     [chap] = noop
(0)     [mschap] = noop
(0)     [digest] = noop
(0) suffix: Checking for suffix after "@"
(0) suffix: No '@' in User-Name = "ems", looking up realm NULL
(0) suffix: No such realm "NULL"
(0)     [suffix] = noop
(0) eap: No EAP-Message, not doing EAP
(0)     [eap] = noop
(0) files: users: Matched entry ems at line 2
(0)     [files] = ok
(0)     [expiration] = noop
(0)     [logintime] = noop
(0)     [pap] = updated
(0)   } # authorize = updated
(0) Found Auth-Type = PAP
(0) # Executing group from file /etc/raddb/sites-enabled/default
(0)   Auth-Type PAP {
(0) pap: Login attempt with password
(0) pap: Comparing with "known good" Cleartext-Password
(0) pap: ERROR: Cleartext password does not match "known good" password
(0) pap: Passwords don't match
(0)     [pap] = reject
(0)   } # Auth-Type PAP = reject
(0) Failed to authenticate the user

Any help will be appreciated. @bontibon

**Comment by arun0704** [comment]
found an issue in code. one should try with example given in cmd folder, that will work.

**Comment by rkapilovich2000** [comment]
I am experiencing the same problem when encrypted password is forwarded to freeradius. When using radclient or radtest with the plain text password it goes through. What could be the reason. The freeradius is running in the debug mode and returns: 
**(3) pap: Comparing with "known good" Cleartext-Password
pap: ERROR: Cleartext password does not match "known good" password
(3) pap: Passwords don't match
(3)     [pap] = reject**

**Comment by 99shoes** [comment]
Thu Aug  1 15:14:19 2024 : Auth: (0) Login incorrect (pap: Cleartext password does not match "known good" password): [ludy/?x@?NS?F????????] (from client localhost port 100) Access-Reject: ludy
I’ve encountered the same issue, and I’d like to know how to solve it.
